In [8]:
import pandas as pd

In [9]:
import numpy as np

In [10]:
customer = pd.read_csv(r'D:\2nd_project\Retails Analytics\customers.csv')

In [11]:
customer.head(50)

   customer_id first_name  last_name  gender   age signup_date region
0        C0000    Patrick     Morgan    Male  18.0  11-07-2025  South
1        C0001       Eric        Lee   Other  36.0  20-09-2021   East
2        C0002     Thomas       Pena  Female   NaN  07-03-2022   East
3        C0003     Dalton      Duran    Male  24.0  29-08-2022  South
4        C0004     Travis    Mcclain    Male  50.0  29-03-2024  South
5        C0005      Brian     Kelley    Male  68.0  21-11-2025  North
6        C0006     Alyssa   Sandoval  Female  47.0  08-02-2025  North
7        C0007    Theresa     Wright    Male  70.0  08-12-2023  South
8        C0008     Alyssa    Estrada    Male  48.0  22-08-2024   East
9        C0009      Karen      Clark  Female  62.0  31-05-2024   East
10       C0010  Christina      Scott    Male  70.0  04-06-2022   West
11       C0011       John   Franklin   Other  51.0  30-06-2021   East
12       C0012     Jerome      Jones    Male  63.0  06-06-2021   East
13       C0013    Richard     Barnes    Male  65.0  15-06-2021  North
14       C0014       Anna    Bennett    Male  26.0  28-06-2021  South
15       C0015       Anne      Greer   Other  32.0  18-09-2021   East
16       C0016    Sabrina      Carey    Male  31.0  21-09-2023  South
17       C0017    Crystal     Adkins    Male  45.0  30-07-2025  North
18       C0018     Amanda      Riley    Male  19.0  21-01-2024   West
19       C0019       Jose   Arellano  Female  20.0  19-05-2021  South
20       C0020   Michelle     Adkins    Male  20.0  28-04-2022  North
21       C0021   Courtney       Roth  Female  25.0  29-12-2023   East
22       C0022       John         Le    Male  22.0  27-11-2025   East
23       C0023   Patricia   Stephens   Other   NaN  30-09-2021  North
24       C0024      Amber    Higgins    Male  56.0  13-01-2024  South
25       C0025     Sharon     Montes   Other  30.0  17-12-2023  South
26       C0026    Vincent      Henry   Other  40.0  15-09-2025  North
27       C0027        Ray       Ross    Male  27.0  17-12-2022   East
28       C0028      Kylie       Long   Other  40.0  16-09-2024   East
29       C0029      Nancy     Murphy    Male  50.0  14-09-2022  South
30       C0030      Craig   Matthews   Other  54.0  06-05-2023  North
31       C0031    Melanie  Patterson    Male  70.0  27-04-2024  North
32       C0032       John    Frazier   Other  31.0  01-07-2022  South
33       C0033    Charles      Jones  Female  28.0  27-07-2025  North
34       C0034      Shawn       Hall   Other  24.0  20-05-2023  South
35       C0035      James      Small   Other  63.0  13-01-2023   West
36       C0036    Anthony   Williams  Female   NaN  18-09-2024  South
37       C0037       John      Silva  Female  61.0  09-05-2025  North
38       C0038      Jamie    Hopkins    Male  40.0  22-09-2025   West
39       C0039   Jonathan      Brown  Female  31.0  20-08-2022  South
40       C0040      Jason        Lee  Female  25.0  23-05-2022   East
41       C0041   Jonathan    Kennedy    Male  47.0  16-05-2023  North
42       C0042     Sherry     Torres   Other  26.0  19-07-2021   West
43       C0043      Kevin     Chavez  Female  63.0  13-02-2024   East
44       C0044      Bryan    Pollard   Other  64.0  14-12-2022  North
45       C0045    Allison      Pratt    Male  38.0  23-06-2024   West
46       C0046     Edward      Green    Male  42.0  04-07-2022   East
47       C0047    Michael     Brewer  Female  56.0  12-11-2025   East
48       C0048    Gregory       Ward   Other  46.0  06-09-2025  South
49       C0049     Robert    Manning   Other  44.0  09-07-2025   East

In [12]:
customer['signup_date'] = pd.to_datetime(customer['signup_date'], dayfirst=True).dt.strftime('%Y-%m-%d')

In [13]:
customer

    customer_id first_name   last_name  gender   age signup_date region
0         C0000    Patrick      Morgan    Male  18.0  2025-07-11  South
1         C0001       Eric         Lee   Other  36.0  2021-09-20   East
2         C0002     Thomas        Pena  Female   NaN  2022-03-07   East
3         C0003     Dalton       Duran    Male  24.0  2022-08-29  South
4         C0004     Travis     Mcclain    Male  50.0  2024-03-29  South
..          ...        ...         ...     ...   ...         ...    ...
811       C0476       John          Le  Female  29.0  2023-11-23   West
812       C0059     Alison      Berger    Male  56.0  2021-11-16   West
813       C0600    Timothy  Cunningham    Male  39.0  2022-04-24  South
814       C0480    Matthew       Moore  Female  27.0  2021-05-23  South
815       C0515  Elizabeth     Alvarez   Other  46.0  2024-07-22   East

[816 rows x 7 columns]

In [14]:
customer= customer.dropna(subset=["age"])

In [15]:
customer

    customer_id first_name   last_name  gender   age signup_date region
0         C0000    Patrick      Morgan    Male  18.0  2025-07-11  South
1         C0001       Eric         Lee   Other  36.0  2021-09-20   East
3         C0003     Dalton       Duran    Male  24.0  2022-08-29  South
4         C0004     Travis     Mcclain    Male  50.0  2024-03-29  South
5         C0005      Brian      Kelley    Male  68.0  2025-11-21  North
..          ...        ...         ...     ...   ...         ...    ...
811       C0476       John          Le  Female  29.0  2023-11-23   West
812       C0059     Alison      Berger    Male  56.0  2021-11-16   West
813       C0600    Timothy  Cunningham    Male  39.0  2022-04-24  South
814       C0480    Matthew       Moore  Female  27.0  2021-05-23  South
815       C0515  Elizabeth     Alvarez   Other  46.0  2024-07-22   East

[776 rows x 7 columns]

In [17]:
print(customer["customer_id"].duplicated())

0      False
1      False
3      False
4      False
5      False
       ...
811     True
812     True
813     True
814     True
815     True
Name: customer_id, Length: 776, dtype: bool

In [18]:
customer = customer.drop_duplicates(subset=["customer_id"])

In [19]:
print(customer["customer_id"].duplicated())

0      False
1      False
3      False
4      False
5      False
       ...
794    False
795    False
796    False
797    False
798    False
Name: customer_id, Length: 760, dtype: bool

In [23]:
def create_age_group(age):
    if age <= 25: return 'Young'
    elif age <= 45: return 'Adult'
    elif age <= 60: return 'Middle-Aged'
    else: return 'Senior'

customer['age_group'] = customer['age'].apply(create_age_group)

C:\Users\affan\AppData\Local\Temp\ipykernel_19684\2535121177.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customer['age_group'] = customer['age'].apply(create_age_group)

In [24]:
customer

,customer_id,first_name,last_name,gender,age,signup_date,region,age_group
0,C0000,Patrick,Morgan,Male,18.0,2025-07-11,South,Young
1,C0001,Eric,Lee,Other,36.0,2021-09-20,East,Adult
3,C0003,Dalton,Duran,Male,24.0,2022-08-29,South,Young
4,C0004,Travis,Mcclain,Male,50.0,2024-03-29,South,Middle-Aged
5,C0005,Brian,Kelley,Male,68.0,2025-11-21,North,Senior
...,...,...,...,...,...,...,...,...
794,C0794,Brent,Brown,Female,36.0,2024-08-21,South,Adult
795,C0795,Emily,Smith,Male,42.0,2025-04-03,South,Adult
796,C0796,Jonathan,Gardner,Other,20.0,2024-03-08,South,Young
797,C0797,Jordan,Smith,Other,56.0,2021-04-29,West,Middle-Aged
798,C0798,Rachel,Porter,Other,39.0,2021-08-12,South,Adult

In [25]:
customer.to_csv('sql_customers.csv', index=False)
print("Customers data cleaned with age_group!")

Customers data cleaned with age_group!

In [27]:
customer['signup_date'] = pd.to_datetime(
    customer['signup_date'],
    errors='coerce'
)

C:\Users\affan\AppData\Local\Temp\ipykernel_19684\1077456497.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customer['signup_date'] = pd.to_datetime(