In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
returns = pd.read_csv(r'D:\2nd_project\Retails Analytics\returns.csv')

In [6]:
returns.head(50)

   return_id order_id return_date     return_reason
0      R0000   O02237  05-03-2025         Defective
1      R0001   O01700  18-03-2025         Defective
2      R0002   O01451  18-02-2025     Late Delivery
3      R0003   O02759  26-10-2024         Defective
4      R0004   O00415  06-08-2025  No Longer Needed
5      R0005   O02110  01-06-2025     Late Delivery
6      R0006   O02845  11-11-2025  No Longer Needed
7      R0007   O00362  01-03-2025         Defective
8      R0008   O01002  28-03-2025         Defective
9      R0009   O02036  13-01-2025     Late Delivery
10     R0010   O01941  15-04-2025     Late Delivery
11     R0011   O01554  08-12-2024         Defective
12     R0012   O01931  10-09-2024     Late Delivery
13     R0013   O00016  10-04-2025         Defective
14     R0014   O01121  07-12-2024  No Longer Needed
15     R0015   O01974  20-12-2025         Defective
16     R0016   O02277  13-05-2024     Late Delivery
17     R0017   O01583  08-02-2025        Wrong Item
18     R0018   O02350  01-07-2025     Late Delivery
19     R0019   O00482  22-12-2024     Late Delivery
20     R0020   O00501  22-02-2025        Wrong Item
21     R0021   O01631  25-05-2024     Late Delivery
22     R0022   O02425  08-05-2024        Wrong Item
23     R0023   O01810  09-09-2024  No Longer Needed
24     R0024   O00753  25-07-2025        Wrong Item
25     R0025   O02631  17-06-2024        Wrong Item
26     R0026   O00590  15-12-2024     Late Delivery
27     R0027   O01591  09-09-2024        Wrong Item
28     R0028   O01410  18-02-2025  No Longer Needed
29     R0029   O00840  18-02-2025     Late Delivery
30     R0030   O02448  21-01-2025         Defective
31     R0031   O01884  11-01-2025     Late Delivery
32     R0032   O02396  24-08-2024        Wrong Item
33     R0033   O00046  02-05-2025     Late Delivery
34     R0034   O01619  01-05-2024        Wrong Item
35     R0035   O02071  10-08-2024         Defective
36     R0036   O02735  03-10-2024         Defective
37     R0037   O00743  22-05-2024  No Longer Needed
38     R0038   O02877  07-01-2025  No Longer Needed
39     R0039   O02943  31-05-2025        Wrong Item
40     R0040   O02323  29-05-2024  No Longer Needed
41     R0041   O00362  23-08-2024  No Longer Needed
42     R0042   O01849  07-04-2025         Defective
43     R0043   O01686  19-09-2025     Late Delivery
44     R0044   O00894  28-11-2025        Wrong Item
45     R0045   O00903  13-01-2025         Defective
46     R0046   O00134  28-02-2025         Defective
47     R0047   O01595  10-08-2025         Defective
48     R0048   O00695  17-05-2025        Wrong Item
49     R0049   O02339  16-12-2024         Defective

In [7]:
# % of null values per column
null_percentage = (returns.isnull().sum() / len(returns)) * 100
null_percentage = null_percentage.round(2)  # Round to 2 decimal places
print(null_percentage)

return_id        0.0
order_id         0.0
return_date      0.0
return_reason    0.0
dtype: float64

In [8]:
returns.dtypes

return_id        object
order_id         object
return_date      object
return_reason    object
dtype: object

In [11]:
returns['return_date'] = pd.to_datetime(
    returns['return_date'],
    dayfirst=True,     # agar aapka date format DD/MM/YYYY hai
    errors='coerce'    # invalid date ko NaT me convert kare
)

In [12]:
invalid_dates = returns['return_date'].isnull().sum()
print(f"Invalid/NULL dates: {invalid_dates}")

Invalid/NULL dates: 1

In [13]:
returns = returns.dropna(subset=['return_date'])

In [14]:
returns['return_date'] = returns['return_date'].dt.strftime('%Y-%m-%d')

In [15]:
returns.head(50)

   return_id order_id return_date     return_reason
0      R0000   O02237  2025-03-05         Defective
1      R0001   O01700  2025-03-18         Defective
2      R0002   O01451  2025-02-18     Late Delivery
3      R0003   O02759  2024-10-26         Defective
4      R0004   O00415  2025-08-06  No Longer Needed
5      R0005   O02110  2025-06-01     Late Delivery
6      R0006   O02845  2025-11-11  No Longer Needed
7      R0007   O00362  2025-03-01         Defective
8      R0008   O01002  2025-03-28         Defective
9      R0009   O02036  2025-01-13     Late Delivery
10     R0010   O01941  2025-04-15     Late Delivery
11     R0011   O01554  2024-12-08         Defective
12     R0012   O01931  2024-09-10     Late Delivery
13     R0013   O00016  2025-04-10         Defective
14     R0014   O01121  2024-12-07  No Longer Needed
15     R0015   O01974  2025-12-20         Defective
16     R0016   O02277  2024-05-13     Late Delivery
17     R0017   O01583  2025-02-08        Wrong Item
18     R0018   O02350  2025-07-01     Late Delivery
19     R0019   O00482  2024-12-22     Late Delivery
20     R0020   O00501  2025-02-22        Wrong Item
21     R0021   O01631  2024-05-25     Late Delivery
22     R0022   O02425  2024-05-08        Wrong Item
23     R0023   O01810  2024-09-09  No Longer Needed
24     R0024   O00753  2025-07-25        Wrong Item
25     R0025   O02631  2024-06-17        Wrong Item
26     R0026   O00590  2024-12-15     Late Delivery
27     R0027   O01591  2024-09-09        Wrong Item
28     R0028   O01410  2025-02-18  No Longer Needed
29     R0029   O00840  2025-02-18     Late Delivery
30     R0030   O02448  2025-01-21         Defective
31     R0031   O01884  2025-01-11     Late Delivery
32     R0032   O02396  2024-08-24        Wrong Item
33     R0033   O00046  2025-05-02     Late Delivery
34     R0034   O01619  2024-05-01        Wrong Item
35     R0035   O02071  2024-08-10         Defective
36     R0036   O02735  2024-10-03         Defective
37     R0037   O00743  2024-05-22  No Longer Needed
38     R0038   O02877  2025-01-07  No Longer Needed
39     R0039   O02943  2025-05-31        Wrong Item
40     R0040   O02323  2024-05-29  No Longer Needed
41     R0041   O00362  2024-08-23  No Longer Needed
42     R0042   O01849  2025-04-07         Defective
43     R0043   O01686  2025-09-19     Late Delivery
44     R0044   O00894  2025-11-28        Wrong Item
45     R0045   O00903  2025-01-13         Defective
46     R0046   O00134  2025-02-28         Defective
47     R0047   O01595  2025-08-10         Defective
48     R0048   O00695  2025-05-17        Wrong Item
49     R0049   O02339  2024-12-16         Defective

In [25]:
returns.to_csv('sql_returns.csv', index=False)
print("Returns data cleaned with age_group!")

Returns data cleaned with age_group!